### ISSUE TITLE
confuse about dataset

### ISSUE THREAD

**Issue by BoyuanJiang** [csjliang/PPR10K#10]
in train_val_images_tif_360p, each scene has six different version photo under source_aug_6, what's the difference between them and which one should be used for training model?

**Comment by csjliang** [comment]
Hi. 

These files are augmented in terms of illuminations or colors from the same input image. These are used for augmentation and simulating complicated situations in the wild. You can use only the original file or use both the original and the augmented files in your training, according to your own requirements. Thanks.
