### ISSUE TITLE
LUT表中负值如何处理

### ISSUE THREAD

**Issue by alexliyang** [csjliang/PPR10K#11]
如何保证lut表中的值在[0,1]之间？ 而且还存在 组合后的lut表的值是否在[0,1]之间，当不在这个区间时，特别是负值时，应该如何处理？

**Comment by csjliang** [comment]
你好，

LUT保存的是从像素值到像素值之间的映射。具体请参考Adaptive 3DLUT论文：https://github.com/HuiZeng/Image-Adaptive-3DLUT。谢谢。
