### ISSUE TITLE
Mismatch between raw data and xmp files

### ISSUE THREAD

**Issue by ZeldaM1** [csjliang/PPR10K#13]
Hi, 
Thanks for sharing your codes and datasets. 
However, during the process of preparing HR datasets, I find out mismatch between raw files and xmp files. 
Though xmp files of target A are complete, xmp files of target B and C are mismatched with raw data. 
Would you mind checking xmp files again and update them? Your help would be appreciated.

Regards,
Huimin

**Comment by csjliang** [comment]
Hi,
The data has been checked. Note each raw file corresponds to 3 xmp files to get 3 versions of different images. Please refer to our paper for more details. Thanks.
