### ISSUE TITLE
关于released模型问题

### ISSUE THREAD

**Issue by SSRheart** [csjliang/PPR10K#14]
请问released模型分别对应论文的哪些结果。
两个released模型的PSNR似乎都远远超过了Table 1给出的PSNR

**Comment by csjliang** [comment]
你好，

感谢关注我们的工作。我们release的模型对应的结果可以根据文件名对应，如‘mask_glc_a’对应文中3D LUT+HRP+GLC，PPR10K-a的结果，注意是对应在LR的列。
