### ISSUE TITLE
how to get the srgb fullsize source and target 

### ISSUE THREAD

**Issue by zhangyunming** [csjliang/PPR10K#3]
good job , the 360p is small for my trainning net, how to get the srgb fullsize source and target ? thanks

**Comment by csjliang** [comment]
Thanks for your attention. 
Please refer to our [instructions](https://github.com/csjliang/PPR10K/blob/master/docs/dataset_usage.md) to customize your data.

**Comment by Maozhiquan** [comment]
您好，请问您得到了全分辨率的srgb的原图和目标图吗？作者给的好像只有原图没有对应的目标图，如果您知道的话可以告诉我吗？可以有偿，真的真的很需要您的交流，如果您愿意给一点小小的指导，我真的感激不尽！！！！v：13628422019
