### ISSUE TITLE
About HR image

### ISSUE THREAD

**Issue by 120326** [csjliang/PPR10K#8]
Thanks for your excellent work on this paper. I have read your tips in _dataset_usage.md_ but still have some questions about the processing of HR images. The file does not mention how I should use the HR images for the testing part of the experiment and thus get the PSNR, Eab, etc., data for the HR images.
Do I need to use Adobe Lightroom to convert the original image format composed of RAW and XMP to TIF and retain the original image size?
I would really appreciate your answer.

**Comment by csjliang** [comment]
Sorry for the late reply. Yes, if you want to get the image of the original size (not 360p), you need to use the CameraRAW and convert them. Thanks!
