### ISSUE TITLE
about Classifier

### ISSUE THREAD

**Issue by alexliyang** [csjliang/PPR10K#9]
the validation.py proposed resnet18_224 as a pretrained test model, how about the classify acc of Classifier2 in model_x.py ?

**Comment by csjliang** [comment]
The classifier2 is much smaller than the resnet18. For our dataset, classifier2 is not enough to handle the complicated problem with so many possibilities. The performance will drop accordingly. We do not make full comparisons but you can try if you are interested. Thanks.
